using (
   x (date not null),
   y integer,
   z (byteint),
   bl01 blob (1024),
   bl02 blob,
   by01 byte,
   by02 byte(4000) not null,
   dec01 decimal(10,2),
   dec02 decimal(10),
   dec03 decimal,
   numb01 NUMBER(10),
   numb02 NUMBER(10, 2),
   numb03 NUMBER,
   numb04 NUMBER(*, 4),
   numeric01 NUMERIC(10, 5),
   numeric02 NUMERIC(10),
   numeric03 NUMERIC,
   d date,
   tm01 time,
   tm02 time(4),
   ts01 timestamp,
   ts02 timestamp(5),
   ch02 CHAR(10),
   ch04 CLOB(12),
   ch05 CHAR VARYING(10),
   ch06 VARCHAR(12),
   ch01 CHAR,
   ch03 CLOB,
   ch07 LONG VARCHAR,
   gr01 GRAPHIC,
   gr02 GRAPHIC(12),
   gr03 LONG VARGRAPHIC,
   gr04 VARGRAPHIC(20),
   prd01 PERIOD(DATE),
   prd02 PERIOD(Time),
   prd03 Period(time(2)),
   prd04 Period(Timestamp),
   prd05 Period (Timestamp(4)),
   prd06 ( period (time(4))),
   prd07 (period (time)),
   xxx blob,
   interval01   interval,
   interval02   interval Day,
   interval03   interval Day(4),
   interval04   interval Day(4) to Hour,
   interval05   interval Day(5) to MINUTE,
   interval06   interval Day(1) to Second,
   interval07   interval Day to hour,
   interval08   interval Day to minute,
   interval09   interval Day to second,
   interval10   interval HOUR,
   interval11   interval HOUR TO SECOND,
   interval12   interval MINUTE TO SECOND,
   interval13   interval MINUTE (4) TO SECOND,
   interval14   interval MINUTE,
   interval15   interval MONTH,
   interval16   interval YEAR,
   interval17   interval YEAR(2),
   interval18   interval YEAR TO MONTH,
   interval19   interval YEAR(2) TO MONTH,
   interval21   (interval),
   interval22   (interval Day),
   interval23   (interval Day(4)),
   interval24   (interval Day(4) to Hour),
   interval25   (interval Day(5) to MINUTE),
   interval26   (interval Day(1) to Second),
   interval27   (interval Day to hour),
   interval28   (interval Day to minute),
   interval29   (interval Day to second),
   interval30   (interval HOUR),
   interval31   (interval HOUR TO SECOND),
   interval32   (interval MINUTE TO SECOND),
   interval33   (interval MINUTE (4) TO SECOND),
   interval34   (interval MINUTE),
   interval35   (interval MONTH),
   interval36   (interval YEAR),
   interval37   (interval YEAR(2)),
   interval38   (interval YEAR TO MONTH),
   interval39   (interval YEAR(2) TO MONTH)
)
insert into y values (?, ?, ?)
;
